doc: create asf-release-notes.md
alc-beijing/alc-site pull request #177
Opened 2023-04-07 08:51 UTC by imbajin

address #173

@WillemJiang @kezhenxu94 @tisonkun could take a review when free

2023-04-10 01:02 UTC, WillemJiang reviewed
提出了一些修改建议。

2023-04-10 01:02 UTC, WillemJiang commented on content/post/apache-policy/asf-release-notes.md
> +4. 如果引入的第三方代码只是某个代码文件中的一小部分, 是否应该用它的 license header 作为整个文件的头 (**待定**)
我觉得需要把基本原则放在前面， 后续结合场景给出相关的指导。 

不建议大家片段化使用第三方代码， 不得已引用的时候需要保留原有代码的 license header。

2023-04-10 01:30 UTC, kezhenxu94 commented on content/post/apache-policy/asf-release-notes.md
> +## 9. 疑难问题
建议加上一个常见的问题: 将第三方源代码从一种编程语言转换成另一种编程语言, 不属于重大修改, 需要保留原 license header, 在一些算法相关的代码中比较常见.

2023-04-11 16:44 UTC, imbajin commented on content/post/apache-policy/asf-release-notes.md
> +## 9. 疑难问题
重构在了 `license header` 分类下

2023-04-17 08:51 UTC, kezhenxu94 approved these changes
基本 OK

2023-04-17 08:51 UTC, kezhenxu94 commented on content/post/apache-policy/asf-release-notes.md
> +   - 二进制包一般也在根目录下 (注: 此项参考其他 ASF 项目, 目前没发现 `ASF` 有硬性要求)
发二进制包甚至不是 Apache 要求的, Apache 要求的只有源码.

2023-04-17 08:51 UTC, kezhenxu94 commented on content/post/apache-policy/asf-release-notes.md
> +4. 引用的第三方`license`, 必须将详细信息附加到我们的 `LICENSE` 文件后, 如果引用的 `LICENSE` 很长, 则需要单独存储并**指向**它们
```suggestion
4. 引用的第三方`license`, 必须将详细信息附加到我们的 `LICENSE` 文件后, 如果引用的 `LICENSE` 很长, 则需要单独存储一个文件并**指向**它们, 如 `LICENSE-<dependency-name>.txt`
```

可以加上如果是标准的(未经修改和增加的) APL2.0 协议, 可以说明是标准的 APL2.0 协议, 然后参考根目录的 APL2.0 协议文件, 不必每个依赖都拷贝一份 Apache license 文件.

2023-04-17 08:51 UTC, kezhenxu94 commented on content/post/apache-policy/asf-release-notes.md
> +- 首先, 大部分开源组织都要求项目的每个**源文件**都有一个明显的 `License` 声明, 这样他人引用时才最容易保留声明/也最直观清晰
```suggestion
- 首先, 大部分开源组织都要求项目的每个**源文件**都有一个明显的 `License` 声明, 这样当他人单独引用某个文件时才最容易保留声明/也最直观清晰
```

2023-04-17 09:11 UTC, imbajin commented on content/post/apache-policy/asf-release-notes.md
> +   - 二进制包一般也在根目录下 (注: 此项参考其他 ASF 项目, 目前没发现 `ASF` 有硬性要求)
> 发二进制包甚至不是 Apache 要求的，Apache 要求的只有源码.

明白, 这里是说**如果发行**二进制包, 则也需要提供对应要求的文件, 但是并不确定二进制包的 `LICENSE` 是否需要放根目录下, 是这个意思, 所以写为  "一般也在根目录下", 或者可考虑加入类似下面的片段: (我在另一个 wiki 页面提过)

![image](https://user-images.githubusercontent.com/17706099/232439578-b460ff7b-7e0d-4e90-8e46-f2074cf66783.png)

2023-04-17 09:21 UTC, imbajin commented on content/post/apache-policy/asf-release-notes.md
> +     3. 如果建议如无必要, 仅保留一个`license header`, 是否需要在 `LICENSE` 文件中说明引入的代码行范围, 不引入的话似乎有点模糊(其他人不知道哪部分代码是 refer 的)
还有这里 `1~3` 的点待定, 似乎也没找到具体/清晰说明

2023-04-17 10:12 UTC, kezhenxu94 commented on content/post/apache-policy/asf-release-notes.md
> +   - 二进制包一般也在根目录下 (注: 此项参考其他 ASF 项目, 目前没发现 `ASF` 有硬性要求)
OK, 我误解了

2023-04-17 10:15 UTC, kezhenxu94 commented on content/post/apache-policy/asf-release-notes.md
> + TODO: 哪些情况是 `WIP` 版本的免责声明可以容忍/携带的呢? 例如说 `GPL` 或是` CC-By` 协议的二进制依赖可以么? 还是说它只适用于一些比较模糊的许可或者是合规性问题呢? (这个需要确认一下)
WIP 基本都可以容忍, 包括使用 GPL/CC-By 等 license 问题

2023-04-18 07:12 UTC, WillemJiang commented on content/post/apache-policy/asf-release-notes.md
> +     3. 如果建议如无必要, 仅保留一个`license header`, 是否需要在 `LICENSE` 文件中说明引入的代码行范围, 不引入的话似乎有点模糊(其他人不知道哪部分代码是 refer 的)
我觉得你提到的这个三个问题还是需要尽力避免片段化代码引用方式来解决。 
对于接口/子类/结构体的使用， 如果是c/c++可以通过include 头文件的方式引用，如果是Java的话可以通过import的方式引入。 对于少量的函数的引用的情况看，建议用重写代码的方式来解决这个问题。

2023-04-18 07:14 UTC, WillemJiang requested changes
疑难问题部分的内容需要在刷新一下。

2023-04-19 03:10 UTC, WillemJiang approved these changes

2023-04-19 07:04 UTC, merged

2023-04-25 01:17 UTC, WillemJiang commented
@imbajin FYI, ALC Beijing 公众号将会发布这篇文章。